import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nerdFont = localFont({
  src: [
    {
      path: "../public/fonts/0xProtoNerdFont-Regular.ttf",
      weight: "400",
    },
  ],
  variable: "--font-nerd-font",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nerdFont.variable}>{children}</body>
    </html>
  );
}
